
char *keyNames[NUM_KEYW]=
{
        "break"     ,
        "char"      ,
        "double"    ,
        "else"      ,
        "for"       ,
        "if"        ,
        "int"       ,
        "return"    ,
        "struct"    ,
        "void"      ,
        "while"
};

char *atomNames[NUM_ATOMS]={
        "BREAK"     ,
        "CHAR"      ,
        "DOUBLE"    ,
        "ELSE"      ,
        "FOR"       ,
        "IF"        ,
        "INT"       ,
        "RETURN"    ,
        "STRUCT"    ,
        "VOID"      ,
        "WHILE"     ,
        "CT_INT"    ,
        "CT_REAL"   ,
        "ID"        ,
        "ESC"       ,
        "CT_CHAR"   ,
        "CT_STRING" ,
        "COMMA"     ,
        "SEMICOL"   ,
        "LPAR"      ,
        "RPAR"      ,
        "LBRACK"    ,
        "RBRACK"    ,
        "LACC"      ,
        "RACC"      ,
        "ADD"       ,
        "SUB"       ,
        "MUL"       ,
        "DOT"       ,
        "DIV"       ,
        "AND"       ,
        "OR"        ,
        "NOT"       ,
        "ASSIGN"    ,
        "EQUAL"     ,
        "NEQUAL"    ,
        "LESS"      ,
        "LESSEQ"    ,
        "GRT"       ,
        "GRTEQ"     ,
        "END"
};
